### ISSUE TITLE
Setup Docker Containers for each service

### ISSUE THREAD

**Issue by DiptoChakrabarty** [DiptoChakrabarty/api-gateway-kong-golang#16]
Currently we are using three services
- kong api gateway
- golang for authentication
- flask api for backend

It would be good to have the golang and flask api running inside docker containers and kong interacting with the containers instead of running them manually

**Comment by diksha1159** [comment]
Hi Dipto,

I'm excited to contribute to this issue! If possible, could you please assign it to me?

Based on the problem description, it seems like the following steps need to be taken to solve the issue:

1. Dockerize the Golang authentication service.
2. Dockerize the Flask backend API.
3. Configure Kong to interact with the Docker containers.

I have experience with Go & Docker, but I'm not familiar with Kong, so there might be a learning curve for me. Additionally, this will be my first open-source contribution, so I'm eager to dive in and make myself familiar with the project. Considering these factors, I estimate that it might take a few days to a week to complete the task.

Your guidance and support throughout this process would be immensely valuable.

Best regards,
Diksha

**Comment by DiptoChakrabarty** [comment]
Sure glad you want to contribute , please go ahead @diksha1159

**Comment by diksha1159** [comment]
Hi Dipto,

Sorry, this is a dumb question, but as a newbie to Kong and APIs, I need some guidance. I'd greatly appreciate it if you could help me with setting up the project by demonstrating how to "Add API endpoints configuration under kong-gateway/config/kong.yaml."

As a newcomer, having an example would be immensely helpful in understanding the structure and syntax required for configuring API endpoints in the Kong YAML file. Once I have this guidance, I believe I'll be able to confidently contribute to the project.

Thank you for your understanding and support.

Best regards,
Diksha

**Comment by DiptoChakrabarty** [comment]
So this is the file that is responsible for rerouting 

kong-gateway/config/kong.yaml

```
# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - name: proxy-service
    url: http://host.docker.internal:8005
    routes:
      - name: all-routes
        paths:
          - /
  - name: login-service
    url: http://host.docker.internal:8005/login
    routes:
      - name: login-route
        paths:
          - /login
```

So the login route requests are proxied to the golang api /login route
similarly the routes starting with / will be routed to the / endpoint to the golang service running in port 8005

The api requests are sent to the kong api which indirectly routes it to the golang service

view this file which contains the curl commands

**Comment by DiptoChakrabarty** [comment]
for example if I add a service like this
```
- name: proxy-service
    url: http://host.docker.internal:8005/example
    routes:
      - name: example-routes
        paths:
          - /example
```

all requests to the kong server hitting  /example route will be redirected to http://host.docker.internal:8005/example route
